var countries = //europa:
                [["Albania", "al", "Macedonia", "Grecja", "Czarnogóra", "Serbia", "Kosowo"],
                ["Andora", "ad", "Hiszpania", "Francja"],
                ["Austria", "at", "Szwajcaria", "Niemcy", "Węgry", "Słowacja", "Czechy", "Włochy", "Słowenia", "Liechtenstein"],
                ["Belgia", "be", "Niemcy", "Holandia", "Luksemburg", "Francja"],
                ["Białoruś", "by", "Polska", "Litwa", "Ukraina", "Rosja", "Łotwa"],
                ["Bośnia i Hercegowina", "ba", "Chorwacja", "Czarnogóra", "Serbia"],
                ["Bułgaria", "bg", "Macedonia", "Grecja", "Rumunia", "Turcja", "Serbia"],
                ["Chorwacja", "hr", "Węgry", "Bośnia i Hercegowina", "Czarnogóra", "Serbia"],
                ["Czarnogóra", "me", "Albania", "Chorwacja", "Bośnia i Hercegowina", "Serbia", "Kosowo"],
                ["Czechy", "cz", "Polska", "Niemcy", "Słowacja", "Austria"],
                ["Dania", "dk", "Niemcy"],
                ["Estonia", "ee", "Rosja", "Łotwa"],
                ["Finlandia", "fi", "Norwegia", "Rosja", "Szwecja"],
                ["Francja", "fr", "Szwajcaria", "Niemcy", "Belgia", "Luksemburg", "Włochy", "Andora", "Monako", "Hiszpania"],
                ["Grecja", "gr", "Albania", "Macedonia", "Turcja", "Bułgaria"],
                ["Hiszpania", "es", "Andora", "Portugalia", "Gibraltar", "Francja", "Maroko"],
                ["Holandia", "nl", "Niemcy", "Belgia"],
                ["Irlandia", "ie", "Wielka Brytania"],
                ["Islandia", "is",],
                ["Kazachstan", "kz", "Turkmenistan", "Chiny", "Kirgistan", "Uzbekistan", "Rosja"],
                ["Liechtenstein", "li", "Szwajcaria", "Austria"],
                ["Litwa", "lt", "Polska", "Łotwa", "Białoruś", "Rosja"],
                ["Luksemburg", "lu", "Belgia", "Niemcy", "Francja"],
                ["Łotwa", "lv", "Litwa", "Estonia", "Białoruś", "Rosja"],
                ["Macedonia", "mk", "Albania", "Grecja", "Bułgaria", "Serbia", "Kosowo"],
                ["Malta", "mt"],
                ["Mołdawia", "md", "Rumunia", "Ukraina"],
                ["Monako", "KOD", "Francja"],
                ["Niemcy", "de", "Szwajcaria", "Polska", "Holandia", "Dania", "Belgia", "Czechy", "Luksemburg", "Francja", "Austria"],
                ["Norwegia", "no", "Finlandia", "Rosja", "Szwecja"],
                ["Polska", "pl", "Niemcy", "Litwa", "Słowacja", "Czechy", "Białoruś", "Ukraina", "Rosja"],
                ["Portugalia", "pt", "Hiszpania"],
                ["Rosja", "ru", "Gruzja", "Chiny", "Białoruś", "Ukraina", "Kazachstan", "Łotwa", "Polska", "Estonia", "Litwa", "Finlandia", "Mongolia", "Norwegia", "Azerbejdżan", "Korea Północna"],
                ["Rumunia", "ro", "Mołdawia", "Węgry", "Ukraina", "Bułgaria", "Serbia"],
                ["San Marino", "KOD", "Włochy"],
                ["Serbia", "rs", "Albania", "Węgry", "Macedonia", "Rumunia", "Chorwacja", "Bośnia i Hercegowina", "Bułgaria"],
                ["Słowacja", "sk", "Polska", "Węgry", "Czechy", "Ukraina", "Austria"],
                ["Słowenia", "si", "Węgry", "Włochy", "Chorwacja", "Austria"],
                ["Szwajcaria", "ch", "Niemcy", "Włochy", "Liechtenstein", "Francja", "Austria"],
                ["Szwecja", "se", "Norwegia", "Finlandia"],
                ["Turcja", "tr", "Syria", "Gruzja", "Irak", "Iran", "Grecja", "Armenia", "Azerbejdżan", "Bułgaria"],
                ["Ukraina", "ua", "Polska", "Mołdawia", "Węgry", "Słowacja", "Białoruś", "Rumunia", "Rosja"],
                ["Watykan", "KOD", "Włochy"],
                ["Węgry", "hu", "Słowacja", "Słowenia", "Rumunia", "Ukraina", "Chorwacja", "Austria", "Serbia"],
                ["Wielka Brytania", "gb", "Irlandia"],
                ["Włochy", "it", "Szwajcaria", "Watykan", "Słowenia", "San Marino", "Francja", "Austria"]
            ];
