var countries = //europa ------------------------------------------------------------
                [["Albania", "al", "Macedonia", "Grecja", "Czarnogóra", "Serbia", "Kosowo"],
                ["Andora", "ad", "Hiszpania", "Francja"],
                ["Austria", "at", "Szwajcaria", "Niemcy", "Węgry", "Słowacja", "Czechy", "Włochy", "Słowenia", "Liechtenstein"],
                ["Belgia", "be", "Niemcy", "Holandia", "Luksemburg", "Francja"],
                ["Białoruś", "by", "Polska", "Litwa", "Ukraina", "Rosja", "Łotwa"],
                ["Bośnia i Hercegowina", "ba", "Chorwacja", "Czarnogóra", "Serbia"],
                ["Bułgaria", "bg", "Macedonia", "Grecja", "Rumunia", "Turcja", "Serbia", "Morze Czarne"],
                ["Chorwacja", "hr", "Węgry", "Bośnia i Hercegowina", "Czarnogóra", "Serbia"],
                ["Czarnogóra", "me", "Albania", "Chorwacja", "Bośnia i Hercegowina", "Serbia", "Kosowo"],
                ["Czechy", "cz", "Polska", "Niemcy", "Słowacja", "Austria"],
                ["Dania", "dk", "Niemcy", "Morze Bałtyckie"],
                ["Estonia", "ee", "Rosja", "Łotwa", "Morze Bałtyckie"],
                ["Finlandia", "fi", "Norwegia", "Rosja", "Szwecja", "Morze Bałtyckie"],
                ["Francja", "fr", "Szwajcaria", "Niemcy", "Belgia", "Luksemburg", "Włochy", "Andora", "Monako", "Hiszpania"],
                ["Grecja", "gr", "Albania", "Macedonia", "Turcja", "Bułgaria"],
                ["Hiszpania", "es", "Andora", "Portugalia", "Gibraltar", "Francja", "Maroko"],
                ["Holandia", "nl", "Niemcy", "Belgia"],
                ["Irlandia", "ie", "Wielka Brytania"],
                ["Islandia", "is",],
                ["Kazachstan", "kz", "Turkmenistan", "Chiny", "Kirgistan", "Uzbekistan", "Rosja"],
                ["Liechtenstein", "li", "Szwajcaria", "Austria"],
                ["Litwa", "lt", "Polska", "Łotwa", "Białoruś", "Rosja", "Morze Bałtyckie"],
                ["Luksemburg", "lu", "Belgia", "Niemcy", "Francja"],
                ["Łotwa", "lv", "Litwa", "Estonia", "Białoruś", "Rosja", "Morze Bałtyckie"],
                ["Macedonia", "mk", "Albania", "Grecja", "Bułgaria", "Serbia", "Kosowo"],
                ["Malta", "mt"],
                ["Mołdawia", "md", "Rumunia", "Ukraina"],
                ["Monako", "KOD", "Francja"],
                ["Niemcy", "de", "Szwajcaria", "Polska", "Holandia", "Dania", "Belgia", "Czechy", "Luksemburg", "Francja", "Austria", "Morze Bałtyckie"],
                ["Norwegia", "no", "Finlandia", "Rosja", "Szwecja"],
                ["Polska", "pl", "Niemcy", "Litwa", "Słowacja", "Czechy", "Białoruś", "Ukraina", "Rosja", "Morze Bałtyckie"],
                ["Portugalia", "pt", "Hiszpania"],
                ["Rosja", "ru", "Gruzja", "Chiny", "Białoruś", "Ukraina", "Kazachstan", "Łotwa", "Polska", "Estonia", "Litwa", "Finlandia", "Mongolia", "Norwegia", "Azerbejdżan", "Korea Północna", "Morze Bałtyckie", "Morze Czarne"],
                ["Rumunia", "ro", "Mołdawia", "Węgry", "Ukraina", "Bułgaria", "Serbia", "Morze Czarne"],
                ["San Marino", "KOD", "Włochy"],
                ["Serbia", "rs", "Albania", "Węgry", "Macedonia", "Rumunia", "Chorwacja", "Bośnia i Hercegowina", "Bułgaria"],
                ["Słowacja", "sk", "Polska", "Węgry", "Czechy", "Ukraina", "Austria"],
                ["Słowenia", "si", "Węgry", "Włochy", "Chorwacja", "Austria"],
                ["Szwajcaria", "ch", "Niemcy", "Włochy", "Liechtenstein", "Francja", "Austria"],
                ["Szwecja", "se", "Norwegia", "Finlandia", "Morze Bałtyckie"],
                ["Turcja", "tr", "Syria", "Gruzja", "Irak", "Iran", "Grecja", "Armenia", "Azerbejdżan", "Bułgaria", "Morze Czarne"],
                ["Ukraina", "ua", "Polska", "Mołdawia", "Węgry", "Słowacja", "Białoruś", "Rumunia", "Rosja", "Morze Czarne"],
                ["Watykan", "KOD", "Włochy"],
                ["Węgry", "hu", "Słowacja", "Słowenia", "Rumunia", "Ukraina", "Chorwacja", "Austria", "Serbia"],
                ["Wielka Brytania", "gb", "Irlandia"],
                ["Włochy", "it", "Szwajcaria", "Watykan", "Słowenia", "San Marino", "Francja", "Austria"],
                // azja --------------------------------------------------------------
                ["Afganistan", "kod", "Chiny", "Iran", "Pakistan", "Tadżykistan", "Turkmenistan", "Uzbekistan"],
                ["Arabia Saudyjska", "kod", "Katar", "Oman", "Irak", "Jamen", "Jordania", "Zjednoczone Emiraty Arabskie", "Kuwejt"],
                ["Armenia", "kod", "Gruzja", "Iran", "Azerbejdżan", "Turcja"],
                ["Azerbejdżan", "kod", "Gruzja", "Iran", "Armenia", "Turcja", "Rosja"],
                ["Bahrajn", "kod"],
                ["Bangladesz", "kod", "Myanmar", "Indie"],
                ["Bhutan", "kod", "Chiny", "Indie"],
                ["Brunei", "kod", "Malezja"],
                ["Chiny", "kod", "Laos", "Bhutan", "Tadżykistan", "Kazachstan", "Mongolia", "Afganistan", "Nepal", "Myanmar", "Kirgistan", "Pakistan", "Korea Północna", "Rosja", "Wietnam", "Indie"],
                ["Cypr", "kod"],
                ["Filipiny", "kod"],
                ["Gruzja", "kod", "Armenia", "Azerbejdżan", "Turcja", "Rosja", "Morze Czarne"],
                ["Indie", "kod", "Chiny", "Nepal", "Myanmar", "Bhutan", "Pakistan", "Bangladesz"],
                ["Indonezja", "kod", "Papua-Nowa Gwinea", "Timor Wschodni", "Malezja"],
                ["Irak", "kod", "Syria", "Arabia Saudyjska", "Iran", "Jordania", "Turcja", "Kuwejt"],
                ["Iran", "kod", "Turkmenistan", "Afganistan", "Irak", "Armenia", "Pakistan", "Azerbejdżan", "Turcja"],
                ["Izrael", "kod", "Syria", "Jordania", "Liban", "Egipt", "Palestyna"],
                ["Japonia", "kod"],
                ["Jemen", "kod", "Arabia Saudyjska", "Oman"],
                ["Jordania", "kod", "Syria", "Arabia Saudyjska", "Irak", "Izrael", "Palestyna"],
                ["Kambodża", "kod", "Laos", "Tajlandia", "Wietnam"],
                ["Katar", "kod", "Arabia Saudyjska"],
                ["Kazachstan", "kod", "Turkmenistan", "Chiny", "Kirgistan", "Uzbekistan", "Rosja"],
                ["Kirgistan", "kod", "Chiny", "Tadżykistan", "Uzbekistan", "Kazachstan"],
                ["Korea Południowa", "kod", "Korea Północna"],
                ["Korea Północna", "kod", "Chiny", "Rosja", "Korea Południowa"],
                ["Kuwejt", "kod", "Arabia Saudyjska", "Irak"],
                ["Laos", "kod", "Chiny", "Myanmar", "Kambodża", "Tajlandia", "Wietnam"],
                ["Liban", "kod", "Syria", "Izrael"],
                ["Malediwy", "kod"],
                ["Malezja", "kod", "Brunei", "Tajlandia", "Indonezja"],
                ["Myanmar", "kod", "Chiny", "Laos", "Tajlandia", "Bangladesz", "Indie"],
                ["Mongolia", "kod", "Chiny", "Rosja"],
                ["Nepal", "kod", "Chiny", "Indie"],
                ["Oman", "kod", "Arabia Saudyjska", "Jemen", "Zjednoczone Emiraty Arabskie"],
                ["Pakistan", "kod", "Chiny", "Afganistan", "Iran", "Indie"],
                ["Singapur", "kod"],
                ["Sri Lanka", "kod"],
                ["Syria", "kod", "Irak", "Jordania", "Izrael", "Turcja", "Liban"],
                ["Tadżykistan", "kod", "Chiny", "Afganistan", "Kirgistan", "Uzbekistan"],
                ["Tajlandia", "kod", "Laos", "Myanmar", "Kambodża", "Malezja"],
                ["Timor Wschodni", "kod", "Indonezja"],
                ["Turkmenistan", "kod", "Afganistan", "Iran", "Uzbekistan", "Kazachstan"],
                ["Uzbekistan", "kod", "Turkmenistan", "Afganistan", "Kirgistan", "Tadżykistan", "Kazachstan"],
                ["Wietnam", "kod", "Chiny", "Laos", "Kambodża"],
                ["Zjednoczone Emiraty Arabskie", "kod", "Arabia Saudyjska", "Oman"]
            ];

var seas = [["Morze Bałtyckie", "sea", "Szwecja", "Finlandia", "Rosja", "Estonia", "Łotwa", "Litwa", "Polska", "Niemcy", "Dania", "Morze Północne", "Ocean Atlantycki"],
            ["Morze Czarne", "sea", "Bułgaria", "Gruzja", "Rosja", "Rumunia", "Turcja", "Ukraina", " Morze Azowskie", "Morze Marmara", "Ocean Atlantycki"]
            ];
