var countries = //europa ------------------------------------------------------------
                [["Albania", "1080_689_2.5", "Macedonia", "Grecja", "Czarnogóra", "Serbia", "Kosowo"],
                ["Andora", "985_699_5.5", "Hiszpania", "Francja"],
                ["Austria", "1049_730_1.5", "Szwajcaria", "Niemcy", "Węgry", "Słowacja", "Czechy", "Włochy", "Słowenia", "Liechtenstein"],
                ["Belgia", "1000_750_2.5", "Niemcy", "Holandia", "Luksemburg", "Francja"],
                ["Białoruś", "1109_766_1.3", "Polska", "Litwa", "Ukraina", "Rosja", "Łotwa"],
                ["Bośnia i Hercegowina", "1067_708_2.5", "Chorwacja", "Czarnogóra", "Serbia"],
                ["Bułgaria", "1106_700_2", "Macedonia", "Grecja", "Rumunia", "Turcja", "Serbia", "Morze Czarne"],
                ["Chorwacja", "1060_719_2.5", "Węgry", "Bośnia i Hercegowina", "Czarnogóra", "Serbia", "Słowenia"],
                ["Czarnogóra", "1075_700_2.5", "Albania", "Chorwacja", "Bośnia i Hercegowina", "Serbia", "Kosowo"],
                ["Czechy", "1051_744_2.5", "Polska", "Niemcy", "Słowacja", "Austria"],
                ["Dania", "1021_782_2.5", "Niemcy", "Morze Bałtyckie"],
                ["Estonia", "1094_797_2.5", "Rosja", "Łotwa", "Morze Bałtyckie"],
                ["Finlandia", "1091_828_1.3", "Norwegia", "Rosja", "Szwecja", "Morze Bałtyckie"],
                ["Francja", "988_724_1.3", "Szwajcaria", "Niemcy", "Belgia", "Luksemburg", "Włochy", "Andora", "Monako", "Hiszpania"],
                ["Grecja", "1092_677_1.5", "Albania", "Macedonia", "Turcja", "Bułgaria"],
                ["Hiszpania", "957_683_1.3", "Andora", "Portugalia", "Gibraltar", "Francja", "Maroko"],
                ["Holandia", "1003_759_2.5", "Niemcy", "Belgia"],
                ["Irlandia", "939_765_2", "Wielka Brytania"],
                ["Islandia", "899_833_1.5"],
                ["Kazachstan", "1309_733_1", "Turkmenistan", "Chiny", "Kirgistan", "Uzbekistan", "Rosja"],
                ["Liechtenstein", "1024_727.5_5.5", "Szwajcaria", "Austria"],
                ["Litwa", "1089_777_2", "Polska", "Łotwa", "Białoruś", "Rosja", "Morze Bałtyckie"],
                ["Luksemburg", "1005_774_4", "Belgia", "Niemcy", "Francja"],
                ["Łotwa", "1093_787_2", "Litwa", "Estonia", "Białoruś", "Rosja", "Morze Bałtyckie"],
                ["Macedonia", "1088_693_3", "Albania", "Grecja", "Bułgaria", "Serbia", "Kosowo"],
                ["Malta", "1053_657_5"],
                ["Mołdawia", "1118_728_2.5", "Rumunia", "Ukraina"],
                ["Monako", "1012_705_3", "Francja"],
                ["Niemcy", "1025_752_1.3", "Szwajcaria", "Polska", "Holandia", "Dania", "Belgia", "Czechy", "Luksemburg", "Francja", "Austria", "Morze Bałtyckie"],
                ["Norwegia", "1016_813_1.3", "Finlandia", "Rosja", "Szwecja"],
                ["Polska", "1071_758_1.3", "Niemcy", "Litwa", "Słowacja", "Czechy", "Białoruś", "Ukraina", "Rosja", "Morze Bałtyckie"],
                ["Portugalia", "934_681_1.5", "Hiszpania"],
                ["Rosja", "1183_799_1", "Gruzja", "Chiny", "Białoruś", "Ukraina", "Kazachstan", "Łotwa", "Polska", "Estonia", "Litwa", "Finlandia", "Mongolia", "Norwegia", "Azerbejdżan", "Korea Północna", "Morze Bałtyckie", "Morze Czarne"],
                ["Rumunia", "1101_720_1.3", "Mołdawia", "Węgry", "Ukraina", "Bułgaria", "Serbia", "Morze Czarne"],
                ["San Marino", "1042_705_5", "Włochy"],
                ["Serbia", "1081_709_2.3", "Albania", "Węgry", "Macedonia", "Rumunia", "Chorwacja", "Bośnia i Hercegowina", "Bułgaria"],
                ["Słowacja", "1071_738_2.3", "Polska", "Węgry", "Czechy", "Ukraina", "Austria"],
                ["Słowenia", "1051_721_3", "Węgry", "Włochy", "Chorwacja", "Austria"],
                ["Szwajcaria", "1017_726_3", "Niemcy", "Włochy", "Liechtenstein", "Francja", "Austria"],
                ["Szwecja", "1043_805_1.3", "Norwegia", "Finlandia", "Morze Bałtyckie"],
                ["Turcja", "1153_676_1.3", "Syria", "Gruzja", "Irak", "Iran", "Grecja", "Armenia", "Azerbejdżan", "Bułgaria", "Morze Czarne"],
                ["Ukraina", "1128_740_1.3", "Polska", "Mołdawia", "Węgry", "Słowacja", "Białoruś", "Rumunia", "Rosja", "Morze Czarne"],
                ["Watykan", "1041_695_5", "Włochy"],
                ["Węgry", "1072_727_1.5", "Słowacja", "Słowenia", "Rumunia", "Ukraina", "Chorwacja", "Austria", "Serbia"],
                ["Wielka Brytania", "968_760_1.3", "Irlandia"],
                ["Włochy", "1032_714_1.3", "Szwajcaria", "Watykan", "Słowenia", "San Marino", "Francja", "Austria"],
                // azja --------------------------------------------------------------
                ["Afganistan", "1327_641_1.3", "Chiny", "Iran", "Pakistan", "Tadżykistan", "Turkmenistan", "Uzbekistan"],
                ["Arabia Saudyjska", "1221_579_1", "Katar", "Oman", "Irak", "Jamen", "Jordania", "Zjednoczone Emiraty Arabskie", "Kuwejt"],
                ["Armenia", "1208_686_2.5", "Gruzja", "Iran", "Azerbejdżan", "Turcja"],
                ["Azerbejdżan", "1224_686_2.5", "Gruzja", "Iran", "Armenia", "Turcja", "Rosja"],
                ["Bahrajn", "1252_595_4"],
                ["Bangladesz", "1470_580_1.3", "Myanmar", "Indie"],
                ["Bhutan", "1468_602_2", "Chiny", "Indie"],
                ["Brunei", "1621_458_2.5", "Malezja"],
                ["Chiny", "1516_650_1", "Laos", "Bhutan", "Tadżykistan", "Kazachstan", "Mongolia", "Afganistan", "Nepal", "Myanmar", "Kirgistan", "Pakistan", "Korea Północna", "Rosja", "Wietnam", "Indie"],
                ["Cypr", "1152_651_3"],
                ["Filipiny", "1665_492_1.3"],
                ["Gruzja", "1200_696_1.3", "Armenia", "Azerbejdżan", "Turcja", "Rosja", "Morze Czarne"],
                ["Indie", "1408_573_1", "Chiny", "Nepal", "Myanmar", "Bhutan", "Pakistan", "Bangladesz"],
                ["Indonezja", "1604_415_1", "Papua-Nowa Gwinea", "Timor Wschodni", "Malezja"],
                ["Irak", "1207_639_1.3", "Syria", "Arabia Saudyjska", "Iran", "Jordania", "Turcja", "Kuwejt"],
                ["Iran", "1268_636_1", "Turkmenistan", "Afganistan", "Irak", "Armenia", "Pakistan", "Azerbejdżan", "Turcja"],
                ["Izrael", "1164_625_2.5", "Syria", "Jordania", "Liban", "Egipt", "Palestyna"],
                ["Japonia", "1707_664_1.3"],
                ["Jemen", "1244_530_1.3", "Arabia Saudyjska", "Oman"],
                ["Jordania", "1172_627_2.5", "Syria", "Arabia Saudyjska", "Irak", "Izrael", "Palestyna"],
                ["Kambodża", "1562_508_1.3", "Laos", "Tajlandia", "Wietnam"],
                ["Katar", "1256_589_3", "Arabia Saudyjska"],
                //["Kazachstan", "", "Turkmenistan", "Chiny", "Kirgistan", "Uzbekistan", "Rosja"],
                ["Kirgistan", "1362_693_1.3", "Chiny", "Tadżykistan", "Uzbekistan", "Kazachstan"],
                ["Korea Południowa", "1651_660_1.3", "Korea Północna"],
                ["Korea Północna", "1633_681_1.3", "Chiny", "Rosja", "Korea Południowa"],
                ["Kuwejt", "1234_616_2.5", "Arabia Saudyjska", "Irak"],
                ["Laos", "1545_551_1.3", "Chiny", "Myanmar", "Kambodża", "Tajlandia", "Wietnam"],
                ["Liban", "1167_644_2.5", "Syria", "Izrael"],
                ["Malediwy", "1389_452_2.5"],
                ["Malezja", "1553_450_1.3", "Brunei", "Tajlandia", "Indonezja"],
                ["Myanmar", "1505_564_1.3", "Chiny", "Laos", "Tajlandia", "Bangladesz", "Indie"],
                ["Mongolia", "1488_722_1", "Chiny", "Rosja"],
                ["Nepal", "1431_608_1.3", "Chiny", "Indie"],
                ["Oman", "1286_556_1.3", "Arabia Saudyjska", "Jemen", "Zjednoczone Emiraty Arabskie"],
                ["Pakistan", "1354_621_1", "Chiny", "Afganistan", "Iran", "Indie"],
                ["Singapur", "1560_437_3.5"],
                ["Sri Lanka", "1429_477_1.3"],
                ["Syria", "1181_651_1.3", "Irak", "Jordania", "Izrael", "Turcja", "Liban"],
                ["Tadżykistan", "1353_674_1.3", "Chiny", "Afganistan", "Kirgistan", "Uzbekistan"],
                ["Tajlandia", "1537_525_1.3", "Laos", "Myanmar", "Kambodża", "Malezja"],
                ["Timor Wschodni", "1681_372_2.5", "Indonezja"],
                ["Turkmenistan", "1290_675_1.3", "Afganistan", "Iran", "Uzbekistan", "Kazachstan"],
                ["Uzbekistan", "1303_694_1.3", "Turkmenistan", "Afganistan", "Kirgistan", "Tadżykistan", "Kazachstan"],
                ["Wietnam", "1578_502_1.3", "Chiny", "Laos", "Kambodża"],
                ["Zjednoczone Emiraty Arabskie", "1273_577_2", "Arabia Saudyjska", "Oman"]
            ];

var seas = [["Morze Bałtyckie", "1063_789_1.3", "Szwecja", "Finlandia", "Rosja", "Estonia", "Łotwa", "Litwa", "Polska", "Niemcy", "Dania", "Morze Północne", "Ocean Atlantycki"],
            ["Morze Czarne", "1151_703_1.3", "Bułgaria", "Gruzja", "Rosja", "Rumunia", "Turcja", "Ukraina", " Morze Azowskie", "Morze Marmara", "Ocean Atlantycki"]
            ];
